### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by motofix** [g0ddest/fixedlength#10]
Is this possible to build release 0.5 and publish to Maven Central ?

**Comment by motofix** [comment]
This is really straightforward using Maven build, but I have no clue how to achieve this using Gradle.

**Comment by g0ddest** [comment]
I've built a release and it was published in github packages.
Also I've created https://issues.sonatype.org/browse/OSSRH-73239 to publish it to maven central.

**Comment by g0ddest** [comment]
It is published now to Maven central

**Comment by motofix** [comment]
Excellent, thanks !
