### ISSUE TITLE
StackOverflowError when SplitLineAfter returns 0

### ISSUE THREAD

**Issue by motofix** [g0ddest/fixedlength#17]
When SplitLineAfter returns 0, the original record is returned leading to an infinite loop.
If SplitLineAfter returns 0 then the record processing should stops.

PR is coming.

**Comment by motofix** [comment]
Would it be possible to create a release after the merge ?

**Comment by g0ddest** [comment]
Thank you! Version 0.7 is ready and deployed.

**Comment by motofix** [comment]
Thanks!

**Comment by motofix** [comment]
The release does not seem to be available on maven central, do you confirm ?

**Comment by g0ddest** [comment]
Sorry, it's still staging in oss repo, soon it will be generally available.

**Comment by motofix** [comment]
Ok, thanks for the update.

**Comment by g0ddest** [comment]
It's already synced with repo1.maven.org : https://repo1.maven.org/maven2/name/velikodniy/vitaliy/fixedlength/0.7/
