### ISSUE TITLE
Allow the use of Reader in addition to InputStream

### ISSUE THREAD

**Issue by mbechto** [g0ddest/fixedlength#36]
This would make reading text from memory more efficient (`char[]->byte[]->char[]` conversion) and less verbose e.g.:

```java
String str = "...";
new FixedLength()
    .registerLineType(LineRecord.class)
    .parse(new StringReader(str));
```

Wdyt @g0ddest?

**Comment by g0ddest** [comment]
Thank you for your contribution! Looks great, please check the PR comment and we could merge it :)

**Comment by g0ddest** [comment]
Merged! Please let me know if you need it to be released in maven central now, or we could collect some changes.

**Comment by mbechto** [comment]
Thanks @g0ddest! Well, actually I was thinking about another feature: Support for Java 14 records. But that sounds like a bit more of a change.

**Comment by g0ddest** [comment]
@mbechto, thats good, but I'd like to keep support for java 8, there are many old projects that could not update to higher java version. But you could raise a conversation maybe there are options to make it without raising minimal java version.

**Comment by mbechto** [comment]
Yep => #39
