### ISSUE TITLE
Parsing String with variable element

### ISSUE THREAD

**Issue by jaysara** [g0ddest/fixedlength#38]
I have a variable segments structure like,

A001{field1-2character}{field2-12characters}{field3-21characters}**C001**{field4-1character}{field5-10characters}{field6-13characters}D001{field7-12character}{field8-2characters}{field9-21characters}

another string can be

A001{field1-2character}{field2-12characters}{field3-21characters}**B001**{field11-5characters}{field12-8characters}{field13-3characters}D001{field7-12character}{field8-2characters}{field9-21characters}**E001**{field20-5characters}{field21-12characters}{field22-2characters}

As mentioned we have segments like A001, B001 , C001, D001, etc.. All segments have fixed format fields. However some segments may or may not be present in a given string. The parser needs to figure out whether a segment is there or not and execure parser logic specific to the segment.

Can this library help ?

**Comment by g0ddest** [comment]
Okay, we could make it if we extend `FixedLine` with regexp or/and predicate functionality and you could pass your conditions there. Will it work for you?

**Comment by g0ddest** [comment]
@jaysara , check out the PR :)

**Comment by g0ddest** [comment]
I've merged predicate solution, try it :)
