### ISSUE TITLE
Option to not remove whitespace

### ISSUE THREAD

**Issue by cbuchmann** [g0ddest/fixedlength#40]
Hi,

Thanks for a great library. I have a case where we have fields that sometimes only contains white spaces. What happens now is that the field is set to null when parsed. I would like some global option to keep the whitespace.

**Comment by g0ddest** [comment]
Hey, @cbuchmann , I've re-readed your issue and looks like I misunderstood the issue. Anyway, I've update code to add support of this case, check out version 0.13 for the solution, take a look at `allowEmptyStrings` attribute of `FixedField` annotation, for example:
`@FixedField(offset = 1, length = 3, padding = Character.MIN_VALUE, allowEmptyStrings = true)`
I'm closing the issue, if you have any more problems don't hesitate to open a new one!
Thank you for great enhancement proposal!
