### ISSUE TITLE
lack support for reading one line at the time

### ISSUE THREAD

**Issue by castixz** [g0ddest/fixedlength#41]
Hi,

first of all thank you for great library.

I have a proposal for enhancement and that is that currently there is no support for reading a file line by line which would be super useful in case of huge files - unfortunately I cannot afford to load all converted POJOs into memory. Introduce reading by chunks would be very beneficial.

Thank you.

Regards

**Comment by g0ddest** [comment]
@castixz , check out `parseAsStream` method instead of `parse`.

**Comment by castixz** [comment]
I'm sorry for wasting your time - I overlooked `parseAsStream` method it therefore immidiately closed the issue. Thanks for your support anyway.
