### ISSUE TITLE
Add Line Split capabilities

### ISSUE THREAD

**Issue by motofix** [g0ddest/fixedlength#5]
It may look weird but we have a case where a line can hold 2 different records, the position of the second record length may be provided in the first record itself.

Example:
```none
HEADERMy Title  26        EmplJoe1      Smith     Developer 07500010012009
CatSnowball  20200103
EmplJoe3      Smith     Developer 
```
The first line contains 2 records:
- "HEADERMy Title  26        " where 26 define the index of the next record
- EmplJoe1      Smith     Developer 07500010012009

PR is coming.

**Comment by g0ddest** [comment]
Merged, thank you!
