### ISSUE TITLE
Are you open to move the build system from Gradle to Maven

### ISSUE THREAD

**Issue by motofix** [g0ddest/fixedlength#9]
Would you accept a PR to move the build system from Gradle to Maven ?

Gradle, yet powerful and flexible, is also complex, confusing and turns to be as chaotic as a project grows. I seriously encourage any project to stick with rigid, sure, predictable Maven build with clear segregation between build declaration (pom) and build cooking (plugins), forcing developers to creates cooking recipes as distributable plugin (versioned, identified, etc) rather than piece of script copied / paste around the globe.

For a simple lib as this one, `mvn package` is the only thing a developer should knows ;-)

**Comment by g0ddest** [comment]
I think that gradle is enough powerful to manage any project and simple enough to add to in any project or build with only one command `gradle build`.

If you love maven you can add pom.xml and I'll accept this PR with no questions, but for me it's convenient to use gradle and I'd like to keep gradle configuration.
